# Generated by Django 3.2.4 on 2021-08-23 21:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='date',
        ),
        migrations.AddField(
            model_name='clinic',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default=1, max_length=56),
            preserve_default=False,
        ),
    ]
